### ISSUE TITLE
Problem with bundle exec rake redmine:plugins:migrate RAILS_ENV=production

### ISSUE THREAD

**Issue by Markster93** [scrum2b/scrum2b#162]
I'm on Debian Stretch, I followed every steps of the installation guide, but everytime I try the command "bundle exec rake redmine:plugins:migrate RAILS_ENV=production", I get this output, and I don't know what to do:

(in /home/marco/redmine-3.3.3-1/apps/redmine/htdocs)
rake aborted!
LoadError: libiconv.so.2: cannot open shared object file: No such file or directory - /home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri/nokogiri.so
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:32:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:32:in `rescue in <top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:28:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie/inliner.rb:2:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie/inliner.rb:2:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie.rb:29:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie.rb:29:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie/rails.rb:6:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie/rails.rb:6:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie-rails.rb:1:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie-rails.rb:1:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/config/application.rb:5:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/Rakefile:5:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
/usr/local/bin/ruby_executable_hooks2.3:15:in `eval'
/usr/local/bin/ruby_executable_hooks2.3:15:in `<main>'
LoadError: cannot load such file -- nokogiri/2.3/nokogiri
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:30:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:30:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie/inliner.rb:2:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie/inliner.rb:2:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie.rb:29:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-3.2.1/lib/roadie.rb:29:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie/rails.rb:6:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie/rails.rb:6:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie-rails.rb:1:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/roadie-rails-1.1.1/lib/roadie-rails.rb:1:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/config/application.rb:5:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/Rakefile:5:in `require'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
/home/marco/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
/usr/local/bin/ruby_executable_hooks2.3:15:in `eval'
/usr/local/bin/ruby_executable_hooks2.3:15:in `<main>'
(See full trace by running task with --trace)

**Comment by klhurley** [comment]
Looks like you need to run 'bundle install' from

home/marco/redmine-3.3.3-1/apps/redmine/htdocs,

it will create some of the Gems, including nokogiri
